### ISSUE TITLE
Add filter for 'forSale' and not 'redeemed' in the Marketplace page

### ISSUE THREAD

**Issue by 0xjim** [WeAreNewt/NonFungibleTime#151]

**Comment by defispartan** [comment]
[ ] By default, Marketplace should display:

```
nfts(where: { owner_not: "0x0000000000000000000000000000000000000000", forSale: true, allowedBuyer_in: [ZERO_ADDRESS, USER_ADDRESS] } )
```

[ ] The `owner_not` part of this filter should be added to the profile query also

[ ] Add forSale toggle 

[ ] Add redeemed toggle

[ ] Search box which toggles for owner, creator or both
