### ISSUE TITLE
forSale toggle in the mint modal

### ISSUE THREAD

**Issue by 0xjim** [WeAreNewt/NonFungibleTime#180]
current state:
`forSale` can only be turned on in the NFT details page

desired state:
- `forSale` can be a toggle on the mint modal
- if toggle is ON, then after the mint is complete (`transaction complete` on the modal), a second modal pops up for the user to set the `price` and the `currency` and a `private sale`

**Comment by defispartan** [comment]
Also refactoring the lastNFT logic to use the transaction log instead of listening for GraphQL update
