### ISSUE TITLE
Mobile view - market place - list of UI issues 

### ISSUE THREAD

**Issue by MareskoZ** [WeAreNewt/NonFungibleTime#214]
env: https://deploy-preview-207--elated-kalam-a67780.netlify.app/profile/0xE11fd1fF6aD8f791Adab2c22B96173De35e4C062

**Issue1:**
dropdowns contain only 1 symbol (impossible to use)

![photo_2022-02-16 10 23 05](https://user-images.githubusercontent.com/18032275/154246309-422ba2d7-9c86-4d26-9784-1193b05e134b.jpeg)

Should be:
the dropdown should be large by horizontal, that text could be readable 

**Issue2:**
the dropdown list under another dropdown 

![photo_2022-02-16 10 23 02](https://user-images.githubusercontent.com/18032275/154246661-fa89035e-d26f-43de-8e0b-13aa522aa047.jpeg)

**Issue3:**
nft cards move out from screen to right 
![photo_2022-02-16 10 22 58](https://user-images.githubusercontent.com/18032275/154246870-6253ef58-7c8e-4496-9942-2a2f2c48e49c.jpeg)

**Tips:**
better to redesign this page and put all dropdowns and inputs in one column

**Comment by defispartan** [comment]
[ ] The input options still overlap on mobile
[ ] Mobile card layout
