### ISSUE TITLE
NFT Modal: Redeem does not work

### ISSUE THREAD

**Issue by ilijabojanovic** [WeAreNewt/NonFungibleTime#256]
Reproduction steps:
1. Go to https://elated-kalam-a67780.netlify.app/
2. Mint new NFT
3. Redeem that NFT

Actual:
Redeem does not work, we can still update price for that Nft

Video:
https://www.screencast.com/t/K3GeZLozGOtC

**Comment by 0xjim** [comment]
As discussed on Mattermost, we decided that people can repurchase already redeemed NFTs
