### ISSUE TITLE
Marketplace page: Filter dropdown options

### ISSUE THREAD

**Issue by lnmunhoz** [WeAreNewt/NonFungibleTime#91]
Decide on what filter options to expose on V1.

![image](https://user-images.githubusercontent.com/4376835/152810827-45adfa12-71a2-40c0-b085-1e2544eb7ec9.png)

- [ ] Only shows for sale
- [ ] Text search field
- [ ] Search for address

**Comment by defispartan** [comment]
Replacing with #151
